[telegram]
token = ""

[ai]
# 各大模型API配置
[ai.openai]
api_key = ""
api_base = "https://aihubmix.com/v1"
model = "gpt-4.1"

[ai.claude]
api_key = ""
api_base = "https://aihubmix.com/v1"
model = "claude-3-opus-20240229"

[ai.deepseek]
api_key = ""
api_base = "https://aihubmix.com/v1"
model = "deepseek-chat"

[ai.qwen]
api_key = ""
api_base = "https://aihubmix.com/v1"
model = "qwen-turbo"
